export interface RawFilterConfig {
  hueDeg?: number;
  hue?: number;
  saturation?: number;
  lightness?: number;
  alpha?: number;
  brightness?: number;
  contrast?: number;
  temperature?: number;
  tint?: number;
  sharpen?: number;
}

export interface RawLayerPatch {
  name?: string;
  visible?: boolean;
  opacity?: number;
  x?: number;
  y?: number;
  blendMode?: string;
  maskInverted?: boolean;
  clipToBelow?: boolean;
  anchor?: "topLeft" | "top_left" | "center" | 0 | 1;
  flipX?: boolean;
  flipY?: boolean;
  rotation?: number;
  scaleX?: number;
  scaleY?: number;
  filterConfig?: RawFilterConfig;
}

export interface RawLayerSnapshot {
  id: number;
  parentId: number | null;
  index: number;
  depth: number;
  kind: "image" | "paint" | "filter" | "group" | "solidColor" | "gradient" | "shape" | "unknown";
  name: string;
  visible: boolean;
  opacity: number;
  x: number;
  y: number;
  blendMode: string;
  hasMask: boolean;
  maskInverted: boolean;
  clipToBelow: boolean;
  width?: number;
  height?: number;
  anchor?: "topLeft" | "center";
  flipX?: boolean;
  flipY?: boolean;
  rotation?: number;
  scaleX?: number;
  scaleY?: number;
  filterConfig?: {
    hueDeg: number;
    saturation: number;
    lightness: number;
    alpha: number;
    brightness: number;
    contrast: number;
    temperature: number;
    tint: number;
    sharpen: number;
  };
  childCount?: number;
  color?: number[];
  direction?: "horizontal" | "vertical" | "diagonalDown" | "diagonalUp";
  stopCount?: number;
  shapeType?: "rectangle" | "roundedRect" | "ellipse" | "line" | "polygon";
  radius?: number;
  pointCount?: number;
  fill?: number[];
  strokeColor?: number[];
  strokeWidth?: number;
}

// @ts-ignore Generated by wasm-bindgen during build.
import * as baselineBindingsModule from "./kimg_wasm_bg.js";
// @ts-ignore Generated by wasm-bindgen during build.
import * as simdBindingsModule from "./kimg_wasm_simd.js";

export type InitInput = import("./kimg_wasm_bg.js").InitInput;
export type InitOutput = import("./kimg_wasm_bg.js").InitOutput;
export type SyncInitInput = import("./kimg_wasm_bg.js").SyncInitInput;

type GeneratedBindingsModule = typeof import("./kimg_wasm_bg.js");
type GeneratedRawCompositionMethods = InstanceType<GeneratedBindingsModule["Composition"]>;

type RawCompositionMethods = GeneratedRawCompositionMethods & {
  get_layer(id: number): RawLayerSnapshot | undefined;
  list_layers(parent_id: number, recursive: boolean): RawLayerSnapshot[];
  update_layer(id: number, patch: RawLayerPatch): boolean;
};

const baselineBindings: GeneratedBindingsModule = baselineBindingsModule;
const simdBindings: GeneratedBindingsModule = simdBindingsModule;

const SIMD_DETECT_BYTES = new Uint8Array([
  0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 123, 3, 2, 1, 0, 10, 10, 1, 8, 0, 65, 0, 253, 15,
  253, 98, 11,
]);

const COMPOSITION_PROXY_HANDLER: ProxyHandler<Composition> = {
  get(target, prop, receiver) {
    if (Reflect.has(target, prop)) {
      return Reflect.get(target, prop, receiver);
    }

    const value = (target as Composition & { _inner: RawCompositionMethods })._inner[
      prop as keyof RawCompositionMethods
    ];
    return typeof value === "function"
      ? value.bind((target as Composition & { _inner: RawCompositionMethods })._inner)
      : value;
  },
  set(target, prop, value, receiver) {
    if (Reflect.has(target, prop)) {
      return Reflect.set(target, prop, value, receiver);
    }

    (target as Composition & { _inner: Record<PropertyKey, unknown> })._inner[prop] = value;
    return true;
  },
};

let activeBindings: GeneratedBindingsModule | null = null;
let cachedSimdSupport: boolean | undefined;

function requireBindings(): GeneratedBindingsModule {
  if (activeBindings === null) {
    throw new Error("kimg WASM is not initialized. Call init() or initSync() first.");
  }

  return activeBindings;
}

function normalizeAsyncInitInput(
  module_or_path:
    | { module_or_path: InitInput | Promise<InitInput> }
    | InitInput
    | Promise<InitInput>,
): { module_or_path: InitInput | Promise<InitInput> } {
  if (
    typeof module_or_path === "object" &&
    module_or_path !== null &&
    "module_or_path" in module_or_path
  ) {
    return module_or_path;
  }

  return { module_or_path };
}

function normalizeSyncInitInput(module: { module: SyncInitInput } | SyncInitInput): {
  module: SyncInitInput;
} {
  if (typeof module === "object" && module !== null && "module" in module) {
    return module;
  }

  return { module };
}

export function simdSupported(): boolean {
  if (cachedSimdSupport !== undefined) {
    return cachedSimdSupport;
  }

  try {
    cachedSimdSupport =
      typeof WebAssembly === "object" &&
      typeof WebAssembly.validate === "function" &&
      WebAssembly.validate(SIMD_DETECT_BYTES);
  } catch {
    cachedSimdSupport = false;
  }

  return cachedSimdSupport;
}

export interface Composition extends RawCompositionMethods {}

export class Composition {
  readonly _inner!: RawCompositionMethods;

  static #fromInner(inner: RawCompositionMethods): Composition {
    const composition = Object.create(Composition.prototype) as Composition;
    Object.defineProperty(composition, "_inner", {
      configurable: false,
      enumerable: false,
      value: inner,
      writable: false,
    });
    return new Proxy(composition, COMPOSITION_PROXY_HANDLER);
  }

  constructor(width: number, height: number) {
    const bindings = requireBindings();
    return Composition.#fromInner(new bindings.Composition(width, height));
  }

  static deserialize(data: Uint8Array): Composition {
    return Composition.#fromInner(requireBindings().Composition.deserialize(data));
  }

  free(): void {
    return this._inner.free();
  }
}

if (typeof Symbol.dispose === "symbol") {
  Composition.prototype[Symbol.dispose] = function (): void {
    if (typeof this._inner[Symbol.dispose] === "function") {
      return this._inner[Symbol.dispose]();
    }

    return this._inner.free();
  };
}

export function contrast_ratio(a: string, b: string): number {
  return requireBindings().contrast_ratio(a, b);
}

export function decode_image(data: Uint8Array): Uint8Array {
  return requireBindings().decode_image(data);
}

export function detect_format(data: Uint8Array): string {
  return requireBindings().detect_format(data);
}

export function dominant_rgb_from_rgba(data: Uint8Array, w: number, h: number): Uint8Array {
  return requireBindings().dominant_rgb_from_rgba(data, w, h);
}

export function extract_palette_from_rgba(
  data: Uint8Array,
  w: number,
  h: number,
  max_colors: number,
): Uint8Array {
  return requireBindings().extract_palette_from_rgba(data, w, h, max_colors);
}

export function hex_to_rgb(hex: string): Uint8Array {
  return requireBindings().hex_to_rgb(hex);
}

export function histogram_rgba(data: Uint8Array, w: number, h: number): Uint32Array {
  return requireBindings().histogram_rgba(data, w, h);
}

export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput {
  const input = normalizeSyncInitInput(module);

  if (simdSupported()) {
    try {
      const output = simdBindings.initSync(input);
      activeBindings = simdBindings;
      return output;
    } catch {
      // Fall through to the baseline artifact if the explicit module is not SIMD.
    }
  }

  const output = baselineBindings.initSync(input);
  activeBindings = baselineBindings;
  return output;
}

export function relative_luminance(hex: string): number {
  return requireBindings().relative_luminance(hex);
}

export function quantize_rgba(
  data: Uint8Array,
  w: number,
  h: number,
  palette: Uint8Array,
): Uint8Array {
  return requireBindings().quantize_rgba(data, w, h, palette);
}

export function rgb_to_hex(r: number, g: number, b: number): string {
  return requireBindings().rgb_to_hex(r, g, b);
}

export default async function init(
  module_or_path?:
    | { module_or_path: InitInput | Promise<InitInput> }
    | InitInput
    | Promise<InitInput>,
): Promise<InitOutput> {
  if (module_or_path !== undefined) {
    const input = normalizeAsyncInitInput(module_or_path);

    if (simdSupported()) {
      try {
        const output = await simdBindings.default(input);
        activeBindings = simdBindings;
        return output;
      } catch {
        // Fall through to the baseline artifact if the explicit module is not SIMD.
      }
    }

    const output = await baselineBindings.default(input);
    activeBindings = baselineBindings;
    return output;
  }

  if (simdSupported()) {
    try {
      const output = await simdBindings.default();
      activeBindings = simdBindings;
      return output;
    } catch {
      // Fall through to the baseline artifact if the SIMD module is unavailable.
    }
  }

  const output = await baselineBindings.default();
  activeBindings = baselineBindings;
  return output;
}
